#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

#Source tutorial clean Function
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
#------------------------------------------------------------------------------
